version: '3.8'
services:
  nagios_sdp_creator_service:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT=
      - SDP_USER_TOKEN=
    build: nagios_sdp_creator
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8080:8080
  jira_issue_creator_service:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT=
      - API_KEY=
      - JIRA_KEY=
    build: jira_issue_creator
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  sdp_monitoring_service:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT=
      - SDP_KEY=
    build: sdp_monitoring
    logging:
      options:
        max-size: "10m"
        max-file: "3"
